name: "Feature Request"
description: "Suggest a new feature or enhancement."
labels: [
  "enhancement"
]

body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Please provide a clear and concise description of the feature you'd like to request."
      placeholder: "Enter feature description here..."
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: "Add any additional context, screenshots, or mockups that could help clarify your feature request."
      placeholder: "Add any additional context or screenshots here..."
    validations:
      required: false
